# Change these first
owner: trujillo66 # Your GitHub organization or username, where this repository lives
repo: apix4.eu.jlb # The name of this repository

sites:
  - name: Vida Automercados
    url: https://vidaautomercados.com
  - name: Alimentos el Maizal
    url: https://alimentoselmaizal.com
  - name: Corporacion JLB
    url: https://corporacionjlb.com
  - name: Agrohorbeca
    url: https://agrohorbeca.com
  - name: Agroinsoca
    url: https://agroinsoca.com
    
#assignees:
#   - trujillo66

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: jlb.apix4.eu
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status JLB
  introTitle: "Página de status, powered by **Upptime**"
  introMessage: Monitoreo **real-time** (https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
